### ISSUE TITLE
Docstring typo in bits-64

### ISSUE THREAD

**Issue by KingMob** [helins/binf.cljc#1]
https://github.com/helins-io/binf.cljc/blob/24973687a47846fce3f17f018cf4960a11a912f3/src/helins/binf.cljc#L2079

Shouldn't this say `f64` in `bits-64`?

**Comment by helins** [comment]
Indeed, took a bit of time but corrected, thanks!

However rebuilding the doc on Cljdoc does not seem to fetch the lastest master commit, so it does not look updated. Would you you happen to know how to force this by any chance?

**Comment by KingMob** [comment]
Cljdoc should automatically pick it up if you change the version. But if you don't want to do that, there's a _very_ faint "Rebuild" link in the upper right of the docs, just to the left of the Github link. 

![Screen Shot 2021-01-11 at 11 01 56 AM](https://user-images.githubusercontent.com/946421/104205584-91540a00-53fc-11eb-958d-1d5dfe94cc70.png)

**Comment by helins** [comment]
Yes that's what I did and I've tried again just now but the doc does not seem to update (although the new build on Cljdoc is successful). Weird... But anyway, thanks!
